//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalAiCtrl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalAiCtrl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item
        ///Master Ball
        ///Ultra Ball
        ///Brightpowder
        ///Great Ball
        ///Poke Ball
        ///Town Map
        ///Bicycle
        ///Moon Stone
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Parlyz Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Potion
        ///Escape Rope
        ///Repel
        ///Max Elixer
        ///Fire Stone
        ///Thunderstone
        ///Water Stone
        ///Item 19
        ///Hp Up
        ///Protein
        ///Iron
        ///Carbos
        ///Lucky Punch
        ///Calcium
        ///Rare Candy
        ///X Accuracy
        ///Leaf Stone
        ///Metal Powder
        ///Nugget
        ///Poke Doll
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Guard Spec
        ///Super Repel
        ///Max Repel
        ///Dire Hit
        ///Item 2D
        ///Fresh  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item_names {
            get {
                return ResourceManager.GetString("item_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ????
        ///Pound
        ///????
        ///Doubleslap
        ///Comet Punch
        ///Mega Punch
        ///PayDay
        ///Fire Punch
        ///Ice Punch
        ///Thunder Punch
        ///Scratch
        ///ViceGrip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand-Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///Sonicboom
        ///Disable
        ///Acid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string move_names {
            get {
                return ResourceManager.GetString("move_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ????
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran F
        ///Nidorina
        ///Nidoqueen
        ///Nidoran M
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pokemon_names {
            get {
                return ResourceManager.GetString("pokemon_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line1
        ///line2
        ///.
        /// </summary>
        internal static string sample_resource {
            get {
                return ResourceManager.GetString("sample_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
